
server:
  port: 8888
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5
  shutdown: graceful

spring:
  application:
    name: config-service
  lifecycle:
    timeout-per-shutdown-phase: 15s # defines a 15-second grace period for requests after SIGTERM
  cloud:
    config:
      server:
        git:
          uri: https://github.com/samaxwell/cnsia-config-repo
          default-label: main
          timeout: 5           # time limit to establish a connection with github
          clone-on-start: true # for resilience
          force-pull: true     # force pull remote, discarding local changes